---
- name: Deploy NSX-T OVAs
  hosts: localhost
  gather_facts: False
  tasks:
    - name: deploy NSX Managers
      deploy_ova:
        ovftool_path: "{{ hostvars['localhost'].ovfToolPath }}"
        datacenter: "{{ hostvars[item]['dc'] }}"
        datastore: "{{ hostvars[item]['datastore'] }}"
        portgroup: "{{ hostvars[item]['portgroup'] }}"
        cluster: "{{ hostvars[item]['cluster'] }}"
        vmname: "{{ item }}"
        hostname: "{{ hostvars[item]['hostname'] }}"
        dns_server: "{{ hostvars['localhost'].dns_server }}"
        dns_domain: "{{ hostvars['localhost'].dns_domain }}"
        ntp_server: "{{ hostvars['localhost'].ntp_server }}"
        gateway: "{{ hostvars[item]['gw'] }}"
        ip_address: "{{ hostvars[item].ansible_ssh_host }}"
        netmask: "{{ hostvars[item]['mask'] }}"
        admin_password: "{{ hostvars[item].ansible_ssh_pass }}"
        cli_password: "{{ hostvars[item].ansible_ssh_pass }}"
        ssh_enabled: "{{ hostvars['localhost'].sshEnabled }}"
        allow_ssh_root_login: "{{ hostvars['localhost'].allowSSHRootAccess }}"
        path_to_ova: "{{ hostvars['localhost'].nsxOvaPath }}"
        ova_file: "{{ hostvars['localhost'].managerOva }}"
        vcenter: "{{ hostvars['localhost'].deployVcIPAddress }}"
        vcenter_user: "{{ hostvars['localhost'].deployVcUser }}"
        vcenter_passwd: "{{ hostvars['localhost'].deployVcPassword }}"
      with_items: "{{ groups['nsxmanagers'] }}"
      async: 7200
      poll: 0
      register: deploy_nsx_man
    - name: Wait 2 minutes before start deploying controllers
      pause: minutes=2
    - name: deploy NSX Controllers
      deploy_ova:
        ovftool_path: "{{ hostvars['localhost'].ovfToolPath }}"
        datacenter: "{{ hostvars[item]['dc'] }}"
        datastore: "{{ hostvars[item]['datastore'] }}"
        portgroup: "{{ hostvars[item]['portgroup'] }}"
        cluster: "{{ hostvars[item]['cluster'] }}"
        vmname: "{{ item }}"
        hostname: "{{ hostvars[item]['hostname'] }}"
        dns_server: "{{ hostvars['localhost'].dns_server }}"
        dns_domain: "{{ hostvars['localhost'].dns_domain }}"
        ntp_server: "{{ hostvars['localhost'].ntp_server }}"
        gateway: "{{ hostvars[item]['gw'] }}"
        ip_address: "{{ hostvars[item].ansible_ssh_host }}"
        netmask: "{{ hostvars[item]['mask'] }}"
        admin_password: "{{ hostvars[item].ansible_ssh_pass }}"
        cli_password: "{{ hostvars[item].ansible_ssh_pass }}"
        ssh_enabled: "{{ hostvars['localhost'].sshEnabled }}"
        allow_ssh_root_login: "{{ hostvars['localhost'].allowSSHRootAccess }}"
        path_to_ova: "{{ hostvars['localhost'].nsxOvaPath }}"
        ova_file: "{{ hostvars['localhost'].controllerOva }}"
        vcenter: "{{ hostvars['localhost'].deployVcIPAddress }}"
        vcenter_user: "{{ hostvars['localhost'].deployVcUser }}"
        vcenter_passwd: "{{ hostvars['localhost'].deployVcPassword }}"
      with_items: "{{ groups['nsxcontrollers'] }}"
      async: 7200
      poll: 0
      register: deploy_nsx_ctrl
    - name: Wait 3 minutes before start deploying Edges
      pause: minutes=3
    - name: deploy NSX Gw OVA
      deploy_ova:
        ovftool_path: "{{ hostvars['localhost'].ovfToolPath }}"
        datacenter: "{{ hostvars[item]['dc'] }}"
        datastore: "{{ hostvars[item]['datastore'] }}"
        portgroup: "{{ hostvars[item]['portgroup'] }}"
        portgroup_ext: "{{ hostvars[item]['portgroupExt'] }}"
        portgroup_transport: "{{ hostvars[item]['portgroupTransport'] }}"
        cluster: "{{ hostvars[item]['cluster'] }}"
        vmname: "{{ item }}"
        hostname: "{{ hostvars[item]['hostname'] }}"
        dns_server: "{{ hostvars['localhost'].dns_server }}"
        dns_domain: "{{ hostvars['localhost'].dns_domain }}"
        ntp_server: "{{ hostvars['localhost'].ntp_server }}"
        gateway: "{{ hostvars[item]['gw'] }}"
        ip_address: "{{ hostvars[item].ansible_ssh_host }}"
        netmask: "{{ hostvars[item]['mask'] }}"
        admin_password: "{{ hostvars[item].ansible_ssh_pass }}"
        cli_password: "{{ hostvars[item].ansible_ssh_pass }}"
        ssh_enabled: "{{ hostvars['localhost'].sshEnabled }}"
        allow_ssh_root_login: "{{ hostvars['localhost'].allowSSHRootAccess }}"
        path_to_ova: "{{ hostvars['localhost'].nsxOvaPath }}"
        ova_file: "{{ hostvars['localhost'].edgeOva }}"
        vcenter: "{{ hostvars['localhost'].deployVcIPAddress }}"
        vcenter_user: "{{ hostvars['localhost'].deployVcUser }}"
        vcenter_passwd: "{{ hostvars['localhost'].deployVcPassword }}"
      with_items: "{{ groups['nsxedges'] }}"
      async: 7200
      poll: 0
      register: deploy_nsx_edges
    - name: Wait 10 minutes before start verifying the deployment
      pause: minutes=10
    - name: Check if NSX Managers deployment has finished
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      with_items: "{{ deploy_nsx_man.results }}"
      retries: 10
    - name: Check if NSX Edges deployment has finished
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      with_items: "{{ deploy_nsx_edges.results }}"
      retries: 10

    - name: Check if NSX Controllers deployment has finished
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      with_items: "{{ deploy_nsx_ctrl.results }}"
      retries: 10


